# DATI ISTAT

In [8]:
import pandas as pd

In [47]:
df_istat = pd.read_csv("../raw_data/ISTAT_raw.csv")
print(df_istat.dtypes)

DATAFLOW                str
FREQ                    str
REF_AREA              int64
DATA_TYPE               str
RESULT                  str
TIME_PERIOD           int64
OBS_VALUE             int64
OBS_STATUS          float64
NOTE_DS             float64
NOTE_REF_AREA       float64
NOTE_DATA_TYPE      float64
NOTE_RESULT         float64
NOTE_TIME_PERIOD    float64
BASE_PER            float64
UNIT_MEAS           float64
UNIT_MULT           float64
dtype: object

# DATAFLOW (str)
"IT1:41_983(1.0)", probabilmente inutile

In [10]:
print(df_istat["DATAFLOW"].unique())
print("________________________________________________")
print(df_istat["DATAFLOW"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["DATAFLOW"].isnull().sum())
print("________________________________________________")

<StringArray>
['IT1:41_983(1.0)']
Length: 1, dtype: str
________________________________________________
DATAFLOW
IT1:41_983(1.0)    573552
Name: count, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________

# FREQ (str)
"A", probabilmente inutile

In [11]:
print(df_istat["FREQ"].unique())
print("________________________________________________")
print(df_istat["FREQ"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["FREQ"].isnull().sum())
print("________________________________________________")

<StringArray>
['A']
Length: 1, dtype: str
________________________________________________
FREQ
A    573552
Name: count, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________

# REF_AREA (int64)
valori da 1001 a 111107, indicano comuni ma da verificare tra gli anni cosa cambia

In [ ]:
print(df_istat["REF_AREA"].unique())
print("________________________________________________")
print(df_istat["REF_AREA"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["REF_AREA"].isnull().sum())
print("________________________________________________")

[  1001   1002   1003 ... 111105 111106 111107]
________________________________________________
REF_AREA
1001      72
1002      72
1003      72
1004      72
1005      54
          ..
111103    24
111104    24
111105    24
111106    24
111107    24
Name: count, Length: 8578, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________

# DATA_TYPE (str)
le due possibilita' della colonna "DATA TYPE" sono:
-KILLINJ , kill injuries? morti?
-ROADACC, road accident? incidenti stradali?

da verificare

In [13]:
print(df_istat["DATA_TYPE"].unique())
print("________________________________________________")
print(df_istat["DATA_TYPE"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["DATA_TYPE"].isnull().sum())
print("________________________________________________")

<StringArray>
['KILLINJ', 'ROADACC']
Length: 2, dtype: str
________________________________________________
DATA_TYPE
KILLINJ    382368
ROADACC    191184
Name: count, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________

# RESULT (str)
F,M, 9 indicano il genere? se si, cosa cazzo e' 9? bambini?
33%, 33%, 33%

In [14]:
print(df_istat["RESULT"].unique())
print("________________________________________________")
print(df_istat["RESULT"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["RESULT"].isnull().sum())
print("________________________________________________")

<StringArray>
['F', 'M', '9']
Length: 3, dtype: str
________________________________________________
RESULT
F    191184
M    191184
9    191184
Name: count, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________

# TIME PERIOD (int64)
Da 2001 a 2024, il numero decresce da 24306 a 23712, meno comuni? fusione di comuni?

In [48]:
print(df_istat["TIME_PERIOD"].unique())
print("________________________________________________")
print(df_istat["TIME_PERIOD"].value_counts().sort_index())
print("________________________________________________")
print("Valori nulli: ", df_istat["TIME_PERIOD"].isnull().sum())
print("________________________________________________")

[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]
________________________________________________
TIME_PERIOD
2001    24303
2002    24306
2003    24306
2004    24300
2005    24303
2006    24303
2007    24303
2008    24303
2009    24300
2010    24282
2011    24276
2012    24276
2013    24276
2014    24177
2015    24141
2016    24000
2017    23934
2018    23862
2019    23745
2020    23712
2021    23712
2022    23712
2023    23703
2024    19017
Name: count, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________

# OBS_VALUE (int64)
numero di incidenti? non sono in ordine ordinato, da capire perche'.
quasi 50% del totale e' 0.

In [49]:
print(df_istat["OBS_VALUE"].unique())
print("________________________________________________")
print(df_istat["OBS_VALUE"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["OBS_VALUE"].isnull().sum())
print("________________________________________________")
print(df_istat["OBS_VALUE"].describe())

[  10    7   13 ... 1081  880  969]
________________________________________________
OBS_VALUE
0       228506
1        69233
2        39073
3        26988
4        20725
         ...
1449         1
1460         1
1081         1
880          1
969          1
Name: count, Length: 1830, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________
count    573552.000000
mean         20.207603
std         245.813966
min           0.000000
25%           0.000000
50%           1.000000
75%           8.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

# OBS_STATUS (float64)

Tutti Nulli

In [50]:
print(df_istat["OBS_STATUS"].unique())
print("________________________________________________")
print(df_istat["OBS_STATUS"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["OBS_STATUS"].isnull().sum())
print("________________________________________________")
print(df_istat["OBS_STATUS"].describe())

[nan]
________________________________________________
Series([], Name: count, dtype: int64)
________________________________________________
Valori nulli:  573552
________________________________________________
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: OBS_STATUS, dtype: float64

# NOTE_* (float64)

sono tutti Nan

In [18]:
print("NOTE_DS:")
print(df_istat["NOTE_DS"].unique())
print(df_istat["NOTE_DS"].isna().sum())
print("________________________________________________")

print("NOTE_REF_AREA:")
print(df_istat["NOTE_REF_AREA"].unique())
print(df_istat["NOTE_REF_AREA"].isna().sum())
print("________________________________________________")

print("NOTE_DATA_TYPE:")
print(df_istat["NOTE_DATA_TYPE"].unique())
print(df_istat["NOTE_DATA_TYPE"].isna().sum())
print("________________________________________________")

print("NOTE_RESULT:")
print(df_istat["NOTE_RESULT"].unique())
print(df_istat["NOTE_RESULT"].isna().sum())
print("________________________________________________")

print("NOTE_TIME_PERIOD:")
print(df_istat["NOTE_TIME_PERIOD"].unique())
print(df_istat["NOTE_TIME_PERIOD"].isna().sum())
print("________________________________________________")

NOTE_DS:
[nan]
573552
________________________________________________
NOTE_REF_AREA:
[nan]
573552
________________________________________________
NOTE_DATA_TYPE:
[nan]
573552
________________________________________________
NOTE_RESULT:
[nan]
573552
________________________________________________
NOTE_TIME_PERIOD:
[nan]
573552
________________________________________________

# ALTRE COLONNE (float64)

sono tutti Nan

In [19]:
print("BASE_PER:")
print(df_istat["BASE_PER"].unique())
print(df_istat["BASE_PER"].isna().sum())
print("________________________________________________")

print("UNIT_MEAS:")
print(df_istat["UNIT_MEAS"].unique())
print(df_istat["UNIT_MEAS"].isna().sum())
print("________________________________________________")

print("UNIT_MULT:")
print(df_istat["UNIT_MULT"].unique())
print(df_istat["UNIT_MULT"].isna().sum())
print("________________________________________________")

BASE_PER:
[nan]
573552
________________________________________________
UNIT_MEAS:
[nan]
573552
________________________________________________
UNIT_MULT:
[nan]
573552
________________________________________________

# DATI SITUAS

In [20]:
df_2024 = pd.read_csv("../raw_data/comuni_2024-12-31.csv", sep=";")
df_2026 = pd.read_csv("../raw_data/comuni_2026-06-21.csv", sep=";")

In [21]:
print(df_2024.columns)
print("_______________________________________")
print(df_2026.columns)

Index(['Codice Ripartizione geografica', 'Codice Regione',
       'Codice Provincia (Storico)', 'Codice Provincia/Uts',
       'Codice Comune (alfanumerico)', 'Codice Comune (numerico)', 'Comune',
       'Comune (dizione straniera)', 'Sigla automobilistica',
       'Capoluogo di Provincia/Uts', 'Capoluogo di Regione',
       'Popolazione legale', 'Anno Censimento', 'Superficie (Kmq)',
       'Anno (Superficie)', 'Popolazione residente',
       'Anno (Popolazione residente)'],
      dtype='str')
_______________________________________
Index(['Codice Ripartizione geografica', 'Codice Regione',
       'Codice Provincia (Storico)', 'Codice Provincia/Uts',
       'Codice Comune (alfanumerico)', 'Codice Comune (numerico)', 'Comune',
       'Comune (dizione straniera)', 'Sigla automobilistica',
       'Capoluogo di Provincia/Uts', 'Capoluogo di Regione',
       'Popolazione legale', 'Anno Censimento', 'Superficie (Kmq)',
       'Anno (Superficie)', 'Popolazione residente',
       'Anno (Popolazione residente)'],
      dtype='str')

In [22]:
print(df_2024.dtypes)
print("_______________________________________")
print(df_2026.dtypes)

Codice Ripartizione geografica    int64
Codice Regione                    int64
Codice Provincia (Storico)        int64
Codice Provincia/Uts              int64
Codice Comune (alfanumerico)      int64
Codice Comune (numerico)          int64
Comune                              str
Comune (dizione straniera)          str
Sigla automobilistica               str
Capoluogo di Provincia/Uts        int64
Capoluogo di Regione              int64
Popolazione legale                int64
Anno Censimento                   int64
Superficie (Kmq)                    str
Anno (Superficie)                 int64
Popolazione residente             int64
Anno (Popolazione residente)      int64
dtype: object
_______________________________________
Codice Ripartizione geografica    int64
Codice Regione                    int64
Codice Provincia (Storico)        int64
Codice Provincia/Uts              int64
Codice Comune (alfanumerico)      int64
Codice Comune (numerico)          int64
Comune                              str
Comune (dizione straniera)          str
Sigla automobilistica               str
Capoluogo di Provincia/Uts        int64
Capoluogo di Regione              int64
Popolazione legale                int64
Anno Censimento                   int64
Superficie (Kmq)                    str
Anno (Superficie)                 int64
Popolazione residente             int64
Anno (Popolazione residente)      int64
dtype: object

# DIFFERENZE TRA 2026 E 2024

In [23]:
print("comuni presenti 2024: ", len(df_2024))
print("comuni presenti 2026: ", len(df_2026))
print("differenza numerica: ", len(df_2026)-len(df_2024), " comuni nel 2026")

comuni presenti 2024:  7896
comuni presenti 2026:  7894
differenza numerica:  -2  comuni nel 2026

Considerando il periodo dello storico dati che si ferma al 2024 ma volendo evitare di fare operazioni su comuni che non esistono pie' trovo i comuni in comune tra il 2024 e oggi con inner join

In [24]:
df_comuni_2426 = df_2024.merge(df_2026, how="inner", on="Codice Comune (numerico)").reset_index(drop=True)

print("Comuni presenti sia nel 2024 che nel 2026: ", len(df_comuni_2426))

Comuni presenti sia nel 2024 che nel 2026:  7516

In [25]:
print(df_comuni_2426.shape)
print("________________________________")
print(df_comuni_2426.head(3))

(7516, 33)
________________________________
   Codice Ripartizione geografica_x  Codice Regione_x  \
0                                 1                 1
1                                 1                 1
2                                 1                 1

   Codice Provincia (Storico)_x  Codice Provincia/Uts_x  \
0                             1                     201
1                             1                     201
2                             1                     201

   Codice Comune (alfanumerico)_x  Codice Comune (numerico)      Comune_x  \
0                            1001                      1001         Agliè
1                            1002                      1002       Airasca
2                            1003                      1003  Ala di Stura

  Comune (dizione straniera)_x Sigla automobilistica_x  \
0                          NaN                      TO
1                          NaN                      TO
2                          NaN                      TO

   Capoluogo di Provincia/Uts_x  ...  Comune (dizione straniera)_y  \
0                             0  ...                           NaN
1                             0  ...                           NaN
2                             0  ...                           NaN

   Sigla automobilistica_y  Capoluogo di Provincia/Uts_y  \
0                       TO                             0
1                       TO                             0
2                       TO                             0

  Capoluogo di Regione_y  Popolazione legale_y  Anno Censimento_y  \
0                      0                  2562               2021
1                      0                  3660               2021
2                      0                   467               2021

   Superficie (Kmq)_y  Anno (Superficie)_y  Popolazione residente_y  \
0             13,1463                 2026                     2585
1             15,7393                 2026                     3695
2             46,3316                 2026                      463

   Anno (Popolazione residente)_y
0                            2024
1                            2024
2                            2024

[3 rows x 33 columns]

In [26]:
print(df_comuni_2426.columns)

Index(['Codice Ripartizione geografica_x', 'Codice Regione_x',
       'Codice Provincia (Storico)_x', 'Codice Provincia/Uts_x',
       'Codice Comune (alfanumerico)_x', 'Codice Comune (numerico)',
       'Comune_x', 'Comune (dizione straniera)_x', 'Sigla automobilistica_x',
       'Capoluogo di Provincia/Uts_x', 'Capoluogo di Regione_x',
       'Popolazione legale_x', 'Anno Censimento_x', 'Superficie (Kmq)_x',
       'Anno (Superficie)_x', 'Popolazione residente_x',
       'Anno (Popolazione residente)_x', 'Codice Ripartizione geografica_y',
       'Codice Regione_y', 'Codice Provincia (Storico)_y',
       'Codice Provincia/Uts_y', 'Codice Comune (alfanumerico)_y', 'Comune_y',
       'Comune (dizione straniera)_y', 'Sigla automobilistica_y',
       'Capoluogo di Provincia/Uts_y', 'Capoluogo di Regione_y',
       'Popolazione legale_y', 'Anno Censimento_y', 'Superficie (Kmq)_y',
       'Anno (Superficie)_y', 'Popolazione residente_y',
       'Anno (Popolazione residente)_y'],
      dtype='str')

In [27]:
df_2426_clean = df_comuni_2426[[
    "Codice Ripartizione geografica_x",
    "Codice Regione_x",
    "Codice Provincia/Uts_x",
    "Codice Comune (alfanumerico)_x", 
    "Codice Comune (numerico)",
    "Comune_x",
    "Sigla automobilistica_x",
    "Capoluogo di Provincia/Uts_x",
    "Capoluogo di Regione_x",
    "Popolazione legale_x",
    "Anno Censimento_x",
    "Superficie (Kmq)_x",
    "Anno (Superficie)_x",
    "Popolazione residente_x",
    "Anno (Popolazione residente)_x"
    ]].copy()

In [28]:
df_2426_clean.columns = [
    "ID_Ripartizione_Geografica",
    "ID_Regione",
    "ID_Provincia/Uts",
    "IDA_Comune", 
    "IDN_Comune",
    "Comune",
    "Sigla_Auto",
    "IS_Capoluogo_Provincia/Uts",
    "IS_Capoluogo_Regione",
    "Pop_Legale",
    "Anno_Pop_Legale",
    "Superficie_Kmq",
    "Anno_Superficie",
    "Pop_Residente",
    "Anno_Pop_Residente"
]

print(df_2426_clean.dtypes)
df_2426_clean.head(3)

ID_Ripartizione_Geografica    int64
ID_Regione                    int64
ID_Provincia/Uts              int64
IDA_Comune                    int64
IDN_Comune                    int64
Comune                          str
Sigla_Auto                      str
IS_Capoluogo_Provincia/Uts    int64
IS_Capoluogo_Regione          int64
Pop_Legale                    int64
Anno_Pop_Legale               int64
Superficie_Kmq                  str
Anno_Superficie               int64
Pop_Residente                 int64
Anno_Pop_Residente            int64
dtype: object

,ID_Ripartizione_Geografica,ID_Regione,ID_Provincia/Uts,IDA_Comune,IDN_Comune,Comune,Sigla_Auto,IS_Capoluogo_Provincia/Uts,IS_Capoluogo_Regione,Pop_Legale,Anno_Pop_Legale,Superficie_Kmq,Anno_Superficie,Pop_Residente,Anno_Pop_Residente
0,1,1,201,1001,1001,Agliè,TO,0,0,2562,2021,"13,1463",2024,2585,2024
1,1,1,201,1002,1002,Airasca,TO,0,0,3660,2021,"15,7393",2024,3695,2024
2,1,1,201,1003,1003,Ala di Stura,TO,0,0,467,2021,"46,3316",2024,463,2024

# PULIZIA COLONNE

In [29]:
df_2426_clean["Superficie_Kmq"] = df_2426_clean["Superficie_Kmq"].astype(str).str.replace(".", "", regex=False)
df_2426_clean["Superficie_Kmq"] = df_2426_clean["Superficie_Kmq"].astype(str).str.replace(",", ".", regex=False).astype(float)
print(df_2426_clean["Superficie_Kmq"].dtypes)

float64

In [30]:
print(df_2426_clean.dtypes)
df_2426_clean.head(3)

ID_Ripartizione_Geografica      int64
ID_Regione                      int64
ID_Provincia/Uts                int64
IDA_Comune                      int64
IDN_Comune                      int64
Comune                            str
Sigla_Auto                        str
IS_Capoluogo_Provincia/Uts      int64
IS_Capoluogo_Regione            int64
Pop_Legale                      int64
Anno_Pop_Legale                 int64
Superficie_Kmq                float64
Anno_Superficie                 int64
Pop_Residente                   int64
Anno_Pop_Residente              int64
dtype: object

,ID_Ripartizione_Geografica,ID_Regione,ID_Provincia/Uts,IDA_Comune,IDN_Comune,Comune,Sigla_Auto,IS_Capoluogo_Provincia/Uts,IS_Capoluogo_Regione,Pop_Legale,Anno_Pop_Legale,Superficie_Kmq,Anno_Superficie,Pop_Residente,Anno_Pop_Residente
0,1,1,201,1001,1001,Agliè,TO,0,0,2562,2021,13.1463,2024,2585,2024
1,1,1,201,1002,1002,Airasca,TO,0,0,3660,2021,15.7393,2024,3695,2024
2,1,1,201,1003,1003,Ala di Stura,TO,0,0,467,2021,46.3316,2024,463,2024

In [31]:
print(df_2426_clean.isnull().sum())

ID_Ripartizione_Geografica     0
ID_Regione                     0
ID_Provincia/Uts               0
IDA_Comune                     0
IDN_Comune                     0
Comune                         1
Sigla_Auto                    92
IS_Capoluogo_Provincia/Uts     0
IS_Capoluogo_Regione           0
Pop_Legale                     0
Anno_Pop_Legale                0
Superficie_Kmq                 0
Anno_Superficie                0
Pop_Residente                  0
Anno_Pop_Residente             0
dtype: int64

In [ ]:
df_2426_clean[df_2426_clean["Comune"].isnull()].head()

In [ ]:
df_2426_clean[df_2426_clean["Sigla_Auto"].isnull()].head(92)

# ID_RIPARTIZIONE GEOGRAFICA (int64)

5 regioni, nord, centro nord, centro sud, sud, isole? oppure nord-est, nord-ovest, centro, sud e isole

In [51]:
print(df_2426_clean["ID_Ripartizione_Geografica"].unique())
print("________________________________________________")
print(df_2426_clean["ID_Ripartizione_Geografica"].value_counts())
print("________________________________________________")
print(df_2426_clean["ID_Ripartizione_Geografica"].describe())

[1 2 3 4 5]
________________________________________________
ID_Ripartizione_Geografica
1    2989
4    1783
2    1385
3     968
5     391
Name: count, dtype: int64
________________________________________________
count    7516.000000
mean        2.361629
std         1.346497
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max         5.000000
Name: ID_Ripartizione_Geografica, dtype: float64

# ID_REGIONE(int64)

In [52]:
print(df_2426_clean["ID_Regione"].unique())
print("________________________________________________")
print(df_2426_clean["ID_Regione"].value_counts())
print("________________________________________________")
print(df_2426_clean["ID_Regione"].describe())

[ 1  2  7  3  4  5  6  8 11  9 10 12 15 13 14 16 17 18 19]
________________________________________________
ID_Regione
3     1501
1     1180
5      558
15     550
18     404
19     391
12     378
8      330
13     305
4      282
9      273
16     257
7      234
11     225
6      215
14     136
17     131
10      92
2       74
Name: count, dtype: int64
________________________________________________
count    7516.000000
mean        8.097924
std         6.010857
min         1.000000
25%         3.000000
50%         6.000000
75%        13.000000
max        19.000000
Name: ID_Regione, dtype: float64

# ID_Provincia/Uts

In [53]:
print(df_2426_clean["ID_Provincia/Uts"].unique())
print("________________________________________________")
print(df_2426_clean["ID_Provincia/Uts"].value_counts())
print("________________________________________________")
print(df_2426_clean["ID_Provincia/Uts"].describe())

[201   2   3   4   5   6   7   8   9 210  11  12  13  14 215  16  17  18
  19  20  21  22  23  24  25  26 227  28  29  30  31  32  33  34  35  36
 237  38  39  40  41  42  43  44  45  46  47 248  49  50  51  52  53  54
  55  56  57 258  59  60  61  62 263  64  65  66  67  68  69  70  71 272
  73  74  75  76  77  78  79 280  81 282 283  84  85  86 287  88  89  93
  94  96  97  98  99 100 101 102 103 108 109 110]
________________________________________________
ID_Provincia/Uts
201    312
4      247
16     243
17     205
6      187
      ...
45      17
88      12
110     10
100      7
32       6
Name: count, Length: 102, dtype: int64
________________________________________________
count    7516.000000
mean       75.857770
std        80.496163
min         2.000000
25%        18.000000
50%        54.000000
75%        89.000000
max       287.000000
Name: ID_Provincia/Uts, dtype: float64

# IDA_Comune

In [54]:
print(df_2426_clean["IDA_Comune"].unique())
print("________________________________________________")
print(df_2426_clean["IDA_Comune"].value_counts())
print("________________________________________________")
print(df_2426_clean["IDA_Comune"].describe())

[  1001   1002   1003 ... 110008 110009 110010]
________________________________________________
IDA_Comune
1001      1
1002      1
1003      1
1004      1
1006      1
         ..
110006    1
110007    1
110008    1
110009    1
110010    1
Name: count, Length: 7516, dtype: int64
________________________________________________
count      7516.000000
mean      42632.479643
std       31172.915019
min        1001.000000
25%       16048.750000
50%       35023.500000
75%       69015.250000
max      110010.000000
Name: IDA_Comune, dtype: float64

# IDN_Comune

In [55]:
print(df_2426_clean["IDN_Comune"].unique())
print("________________________________________________")
print(df_2426_clean["IDN_Comune"].value_counts())
print("________________________________________________")
print(df_2426_clean["IDN_Comune"].describe())

[  1001   1002   1003 ... 110008 110009 110010]
________________________________________________
IDN_Comune
1001      1
1002      1
1003      1
1004      1
1006      1
         ..
110006    1
110007    1
110008    1
110009    1
110010    1
Name: count, Length: 7516, dtype: int64
________________________________________________
count      7516.000000
mean      42632.479643
std       31172.915019
min        1001.000000
25%       16048.750000
50%       35023.500000
75%       69015.250000
max      110010.000000
Name: IDN_Comune, dtype: float64

# Comune

Comune                         1
Sigla_Auto                    92
IS_Capoluogo_Provincia/Uts     0
IS_Capoluogo_Regione           0
Pop_Legale                     0
Anno_Pop_Legale                0
Superficie_Kmq                 0
Anno_Superficie                0
Pop_Residente                  0
Anno_Pop_Residente             0
dtype: int64